# Generated by Django 2.0.2 on 2019-05-06 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Microcurriculum',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('vigencia', models.CharField(max_length=20, verbose_name='Vigencia')),
                ('descripcion_general', models.TextField(verbose_name='Descripcion General')),
                ('proposito', models.TextField(verbose_name='Propósito')),
                ('objetivo_general', models.TextField(verbose_name='Objetivo General')),
                ('objetivo_especifico', models.TextField(verbose_name='Objetivo Especifico')),
                ('contenido_resumido', models.TextField(verbose_name='Contenido Resumido')),
                ('actividades_asis_oblig', models.CharField(max_length=255, verbose_name='Actividades de Asistencia Obligatoria')),
                ('bibliografia_basica', models.TextField(verbose_name='Bibliografia Basica')),
                ('bibliografia_complementaria', models.TextField(verbose_name='Bibliografía Complementaria')),
                ('metodologia', models.TextField(verbose_name='Metodologia')),
            ],
            options={
                'verbose_name': 'Microcurriculo',
                'verbose_name_plural': 'Microcurriculos',
                'ordering': ['id'],
            },
        ),
    ]
