# Generated by Django 2.0.2 on 2019-05-06 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unity',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('tema', models.CharField(max_length=20, verbose_name='Tema')),
                ('subtema', models.TextField(verbose_name='Subtema')),
                ('num_semanas', models.SmallIntegerField(verbose_name='Numero de semanas')),
                ('id_microcurriculos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Microcurriculum', verbose_name='Microcurriculo')),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
                'ordering': ['id'],
            },
        ),
    ]
