# Generated by Django 2.0.2 on 2019-05-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_evaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='actividad',
            field=models.CharField(max_length=255, verbose_name='Actividad'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='porcentaje',
            field=models.CharField(max_length=255, verbose_name='Porcentaje'),
        ),
        migrations.AlterField(
            model_name='microcurriculum',
            name='vigencia',
            field=models.CharField(max_length=255, verbose_name='Vigencia'),
        ),
        migrations.AlterField(
            model_name='unity',
            name='tema',
            field=models.CharField(max_length=255, verbose_name='Tema'),
        ),
    ]
