# Generated by Django 2.0.2 on 2019-05-14 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190507_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=255, verbose_name='Codigo')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('num_creditos', models.SmallIntegerField(verbose_name='Numero de Creditos')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Curso_asignado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nivel', models.SmallIntegerField(verbose_name='Nivel')),
                ('version_pensum', models.SmallIntegerField(verbose_name='Version del Pensum')),
                ('area', models.CharField(max_length=255, verbose_name='Area')),
                ('horas_t', models.SmallIntegerField(verbose_name='Horas Teoricas')),
                ('horas_p', models.SmallIntegerField(verbose_name='Horas Practicas')),
                ('horas_tp', models.SmallIntegerField(verbose_name='Horas Teorico-Practica')),
                ('horas_especiales', models.SmallIntegerField(verbose_name='Horas Especiales')),
                ('habilitable', models.BooleanField(verbose_name='Habilitable')),
                ('validable', models.BooleanField(verbose_name='Validable')),
                ('clasificable', models.BooleanField(verbose_name='Clasificable')),
                ('prereq', models.CharField(max_length=255, verbose_name='Prerrequisitos')),
                ('correq', models.CharField(max_length=255, verbose_name='Corequisitos')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Curso Asignado',
                'verbose_name_plural': 'Cursos Asignados',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Curso_programado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('semestre', models.CharField(max_length=255, verbose_name='Semestre')),
                ('id_curso_asignado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Curso_asignado', verbose_name='Curso Asignado')),
                ('id_microcurriculos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Microcurriculum', verbose_name='Microcurriculo')),
            ],
            options={
                'verbose_name': 'Curso Programado',
                'verbose_name_plural': 'Cursos Programados',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_progr', models.CharField(max_length=255, verbose_name='Programa')),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='curso_asignado',
            name='id_programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Programa', verbose_name='Programa'),
        ),
    ]
