# Generated by Django 2.0.2 on 2019-07-08 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190524_2131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso_programado',
            options={'ordering': ['id_microcurriculos'], 'verbose_name': 'Curso Programado', 'verbose_name_plural': 'Cursos Programados'},
        ),
        migrations.RemoveField(
            model_name='microcurriculum',
            name='desde',
        ),
        migrations.RemoveField(
            model_name='microcurriculum',
            name='hasta',
        ),
    ]
