# Generated by Django 2.0.2 on 2019-07-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190708_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semestres',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripcion')),
            ],
        ),
    ]
