# Generated by Django 2.0.2 on 2019-11-25 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_evaluation_2_microcurriculum_2_unity_2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semestres',
            options={'ordering': ['id'], 'verbose_name': 'Semestre', 'verbose_name_plural': 'Semestres'},
        ),
    ]
