# Generated by Django 2.0.2 on 2019-11-25 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20191125_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation_2',
            name='id_microcurriculos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Microcurriculum_2', verbose_name='Microcurriculo'),
        ),
        migrations.AlterField(
            model_name='unity_2',
            name='id_microcurriculos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Microcurriculum_2', verbose_name='Microcurriculo'),
        ),
    ]
