# Generated by Django 2.0.2 on 2019-11-30 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20191125_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('soli', models.CharField(max_length=255, verbose_name='Solicitud')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('curso_destino', models.CharField(max_length=255, verbose_name='Curso Destino')),
                ('pensum_destino', models.CharField(max_length=255, verbose_name='Pensum Destino')),
                ('curso_propietario', models.CharField(max_length=255, verbose_name='Curso Propietario')),
                ('pensum_propietario', models.CharField(max_length=255, verbose_name='Pensum Propietario')),
                ('semestre_asignar', models.CharField(max_length=255, verbose_name='Semestre a asignar')),
                ('microcurriculo', models.CharField(max_length=255, verbose_name='Microcurriculo')),
                ('usuario', models.CharField(max_length=255, verbose_name='Usuario que realizo la peticion')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'ordering': ['id'],
            },
        ),
    ]
