# Generated by Django 2.0.2 on 2019-12-02 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='microcurriculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Microcurriculum_2', verbose_name='Microcurriculo'),
        ),
    ]
