# Generated by Django 2.0.2 on 2020-02-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200220_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='archivo',
            field=models.FileField(upload_to='files/', verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(max_length=255, verbose_name='Estado'),
        ),
    ]
