# Generated by Django 2.0.2 on 2020-02-21 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_versiones'),
    ]

    operations = [
        migrations.AddField(
            model_name='versiones',
            name='id_microcurriculos_2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.Microcurriculum_2', verbose_name='Microcurriculo fantasma'),
        ),
        migrations.AlterField(
            model_name='versiones',
            name='id_microcurriculos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Microcurriculum', verbose_name='Microcurriculo final'),
        ),
    ]
