# Generated by Django 2.0.2 on 2020-02-21 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200221_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versiones',
            name='id_microcurriculos_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Microcurriculum_2', verbose_name='Microcurriculo fantasma'),
        ),
    ]
