# Generated by Django 2.0.2 on 2020-02-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_solicitud_coordinador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='coordinador',
            field=models.CharField(max_length=255, verbose_name='Coordinador que estudio la peticion'),
        ),
    ]
