# Generated by Django 2.0.2 on 2020-03-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20200307_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='tipo',
            field=models.CharField(default='', max_length=255, verbose_name='Tipo'),
        ),
    ]
