# Generated by Django 2.0.2 on 2020-03-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_solicitud_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='tipo',
            field=models.CharField(max_length=255, verbose_name='Tipo'),
        ),
    ]
