# Generated by Django 2.0.2 on 2020-03-19 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20200319_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de creacion'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de actualizacion'),
        ),
        migrations.AddField(
            model_name='versiones',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de creacion'),
        ),
        migrations.AddField(
            model_name='versiones',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de actualizacion'),
        ),
    ]
