# Generated by Django 2.0.2 on 2020-03-27 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20200327_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versiones',
            name='comentarios',
            field=models.FileField(null=True, upload_to='files/', verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='versiones',
            name='id_microcurriculos_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Microcurriculum_2', verbose_name='Microcurriculo fantasma'),
        ),
    ]
