# Generated by Django 2.0.2 on 2020-06-03 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_userrol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrol',
            options={'ordering': ['id'], 'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AddField(
            model_name='userrol',
            name='cursos',
            field=models.TextField(null=True),
        ),
    ]
