# Generated by Django 2.0.2 on 2020-07-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_userrol_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrol',
            name='cursos',
            field=models.ManyToManyField(null=True, to='core.Curso_asignado', verbose_name='Cursos'),
        ),
    ]
