# Generated by Django 2.0.2 on 2020-07-13 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20200708_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrol',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Programa'),
        ),
    ]
